package ofp

const OFPP_V13 = 4
const OFPP_V15 = 6

func ExpectedType(msgType uint8) uint8 {
	switch msgType {
	case 2, 5, 7, 18, 20, 22, 24, 26:
		return msgType + 1
	default:
		return msgType
	}
}

func IsAsymmetric(msgType uint8) bool {
	switch msgType {
	case 1, 10, 11, 12:
		return true
	default:
		return false
	}
}

const (

	// Symetric controller/switch messages

	OFPT_HELLO        = 0
	OFPT_ERROR        = 1
	OFPT_ECHO_REQUEST = 2
	OFPT_ECHO_REPLY   = 3
	OFPT_EXPERIMENTER = 4

	// Symetric controller/switch messages

	OFPT_FEATURES_REQUEST   = 5
	OFPT_FEATURES_REPLY     = 6
	OFPT_GET_CONFIG_REQUEST = 7
	OFPT_GET_CONFIG_REPLY   = 8
	OFPT_SET_CONFIG         = 9

	// Asymmetric messages

	OFPT_PACKET_IN    = 10
	OFPT_FLOW_REMOVED = 11
	OFPT_PORT_STATUS  = 12

	// Symetric controller/switch messages

	OFPT_PACKET_OUT = 13
	OFPT_FLOW_MOD   = 14
	OFPT_GROUP_MOD  = 15
	OFPT_PORT_MOD   = 16
	OFPT_TABLE_MOD  = 17

	OFPT_MULTIPART_REQUEST = 18
	OFPT_MULTIPART_REPLY   = 19

	OFPT_BARRIER_REQUEST          = 20
	OFPT_BARRIER_REPLY            = 21
	OFPT_QUEUE_GET_CONFIG_REQUEST = 22
	OFPT_QUEUE_GET_CONFIG_REPLY   = 23

	OFPT_ROLE_REQUEST = 24
	OFPT_ROLE_REPLY   = 25

	OFPT_GET_ASYNC_REQUEST = 26
	OFPT_GET_ASYNC_REPLY   = 27
	OFPT_SET_ASYNC         = 28

	OFPT_METER_MOD = 29
)

// Match oxm type
const (
	OFPMT_STANDARD = iota
	OFPMT_OXM
)

// Match oxm classes
const (
	OFPXMC_NXM_0          = 0x0000
	OFPXMC_NXM_1          = 0x0001
	OFPXMC_OPENFLOW_BASIC = 0x8000
	OFPXMC_EXPERIMENTER   = 0xffff
)

// oxm fields
const (
	OFPXMT_OFB_IN_PORT = iota
	OFPXMT_OFB_IN_PHY_PORT
	OFPXMT_OFB_METADATA
	OFPXMT_OFB_ETH_DST
	OFPXMT_OFB_ETH_SRC
	OFPXMT_OFB_ETH_TYPE
	OFPXMT_OFB_VLAN_VID
	OFPXMT_OFB_VLAN_PCP
	OFPXMT_OFB_IP_DSCP
	OFPXMT_OFB_IP_ECN
	OFPXMT_OFB_IP_PROTO
	OFPXMT_OFB_IPV4_SRC
	OFPXMT_OFB_IPV4_DST
	OFPXMT_OFB_TCP_SRC
	OFPXMT_OFB_TCP_DST
	OFPXMT_OFB_UDP_SRC
	OFPXMT_OFB_UDP_DST
	OFPXMT_OFB_SCTP_SRC
	OFPXMT_OFB_SCTP_DST
	OFPXMT_OFB_ICMPV4_TYPE
	OFPXMT_OFB_ICMPV4_CODE
	OFPXMT_OFB_ARP_OP
	OFPXMT_OFB_ARP_SPA
	OFPXMT_OFB_ARP_TPA
	OFPXMT_OFB_ARP_SHA
	OFPXMT_OFB_ARP_THA
	OFPXMT_OFB_IPV6_SRC
	OFPXMT_OFB_IPV6_DST
	OFPXMT_OFB_IPV6_FLABEL
	OFPXMT_OFB_ICMPV6_TYPE
	OFPXMT_OFB_ICMPV6_CODE
	OFPXMT_OFB_IPV6_ND_TARGET
	OFPXMT_OFB_IPV6_ND_SLL
	OFPXMT_OFB_IPV6_ND_TLL
	OFPXMT_OFB_MPLS_LABEL
	OFPXMT_OFB_MPLS_TC
	OFPXMT_OFB_MPLS_BOS
	OFPXMT_OFB_PBB_ISID
	OFPXMT_OFB_TUNNEL_ID
	OFPXMT_OFB_IPV6_EXTHDR
	OFPXMT_OFB_PBB_UCA
	OFPXMT_OFB_TCP_FLAGS
	OFPXMT_OFB_ACTSET_OUTPUT
	OFPXMT_OFB_PACKET_TYPE
)

const (
	OFPVID_PRESENT = 0x1000
	OFPVID_NONE    = 0x0000
)

const (
	OFP_VLAN_NONE = OFPVID_NONE
)
